let
    Source =
        Folder.Files(
            "C:\Users\"
        ),

    #"Filtered Export CSV Files" =
        Table.SelectRows(
            Source,
            each
                Text.Lower([Extension]) = ".csv"
                    and Text.StartsWith(
                        [Name],
                        "Export",
                        Comparer.OrdinalIgnoreCase
                    )
                    and Record.FieldOrDefault(
                        [Attributes],
                        "Hidden",
                        false
                    ) <> true
        ),

    #"Sorted Files" =
        Table.Sort(
            #"Filtered Export CSV Files",
            {
                {"Name", Order.Ascending}
            }
        ),

    #"Imported Files" =
        Table.AddColumn(
            #"Sorted Files",
            "Imported Data",
            (CurrentFile as record) as table =>
                let
                    CsvData =
                        Csv.Document(
                            CurrentFile[Content],
                            [
                                Delimiter = ",",
                                Encoding = 1252,
                                QuoteStyle = QuoteStyle.Csv
                            ]
                        ),

                    PromotedHeaders =
                        Table.PromoteHeaders(
                            CsvData,
                            [PromoteAllScalars = true]
                        ),

                    AddedSourceFile =
                        Table.AddColumn(
                            PromotedHeaders,
                            "Source File",
                            each CurrentFile[Name],
                            type text
                        )
                in
                    AddedSourceFile,
            type table
        ),

    #"Combined Files" =
        if Table.RowCount(#"Imported Files") = 0 then
            #table({}, {})
        else
            Table.Combine(
                #"Imported Files"[Imported Data]
            ),

    TypeMap =
        {
            {"Serial", type text},
            {"export_date", type datetime},
            {"Source File", type text},
            {"Managed DN", type text},
            {"Description", type text},
            {"Subject Alt Name (DNS)", type text},
            {"Common Name", type text},
            {"Valid To", type datetime},
            {"C1. ITSI Correlation ID", type text},
            {"D4. Navigator ID/OrderBook", type text},
            {"B4. Change Number", type text},
            {
                "E1. Early Additional Notification (120 Days)",
                type text
            },
            {"A2. ServiceFirst Group", type text},
            {"Z6. Service Owner Email", type text},
            {
                "E4. Authoriser/Escalation Notification",
                type text
            },
            {"C3. IT Service Instance", type text},
            {"A3. ServiceFirst Group Email", type text},
            {
                "E2. First Additional Notification (60 Days)",
                type text
            },
            {"A1. Requester Email", type text},
            {"D2. Project Name", type text},
            {"D3. Project Manager", type text}
        },

    ExistingTypeMap =
        List.Select(
            TypeMap,
            each
                List.Contains(
                    Table.ColumnNames(#"Combined Files"),
                    _{0}
                )
        ),

    #"Changed Types" =
        Table.TransformColumnTypes(
            #"Combined Files",
            ExistingTypeMap
        )
in
    #"Changed Types"
