let
    Source =
        Folder.Files(
            "C:\Users\\Downloads"
        ),

    #"Filtered Export CSV Files" =
        Table.SelectRows(
            Source,
            each
                Text.Lower([Extension]) = ".csv"
                    and Text.StartsWith(
                        [Name],
                        "Export_",
                        Comparer.OrdinalIgnoreCase
                    )
                    and Record.FieldOrDefault(
                        [Attributes],
                        "Hidden",
                        false
                    ) <> true
        ),

    #"Sorted Files" =
        Table.Sort(
            #"Filtered Export CSV Files",
            {
                {"Name", Order.Ascending}
            }
        ),

    #"Imported Files" =
        Table.AddColumn(
            #"Sorted Files",
            "Imported Data",
            (CurrentFile as record) as table =>
                let
                    // Extract yyyy-MM-dd from:
                    // Export_2026-07-23_....csv
                    ExportDate =
                        try
                            Date.FromText(
                                Text.Middle(
                                    CurrentFile[Name],
                                    7,
                                    10
                                ),
                                [
                                    Format = "yyyy-MM-dd",
                                    Culture = "en-US"
                                ]
                            )
                        otherwise
                            try Date.From(CurrentFile[Date modified])
                            otherwise null,

                    CsvData =
                        Csv.Document(
                            CurrentFile[Content],
                            [
                                Delimiter = ",",
                                Encoding = 1252,
                                QuoteStyle = QuoteStyle.Csv
                            ]
                        ),

                    PromotedHeaders =
                        Table.PromoteHeaders(
                            CsvData,
                            [PromoteAllScalars = true]
                        ),

                    AddedSourceFile =
                        Table.AddColumn(
                            PromotedHeaders,
                            "Source File",
                            each CurrentFile[Name],
                            type text
                        ),

                    AddedExportDate =
                        Table.AddColumn(
                            AddedSourceFile,
                            "export_date",
                            each ExportDate,
                            type nullable date
                        )
                in
                    AddedExportDate,
            type table
        ),

    #"Combined Files" =
        if Table.RowCount(#"Imported Files") = 0 then
            #table({}, {})
        else
            Table.Combine(
                #"Imported Files"[Imported Data]
            ),

    TypeMap =
        {
            {"Serial", type text},
            {"export_date", type date},
            {"Source File", type text},
            {"Managed DN", type text},
            {"Description", type text},
            {"Subject Alt Name (DNS)", type text},
            {"Common Name", type text},
            {"Valid To", type datetime},
            {"C1. ITSI Correlation ID", type text},
            {"D4. Navigator ID/OrderBook", type text},
            {"B4. Change Number", type text},
            {
                "E1. Early Additional Notification (120 Days)",
                type text
            },
            {"A2. ServiceFirst Group", type text},
            {"Z6. Service Owner Email", type text},
            {
                "E4. Authoriser/Escalation Notification",
                type text
            },
            {"C3. IT Service Instance", type text},
            {"A3. ServiceFirst Group Email", type text},
            {
                "E2. First Additional Notification (60 Days)",
                type text
            },
            {"A1. Requester Email", type text},
            {"D2. Project Name", type text},
            {"D3. Project Manager", type text}
        },

    ExistingTypeMap =
        List.Select(
            TypeMap,
            each
                List.Contains(
                    Table.ColumnNames(#"Combined Files"),
                    _{0}
                )
        ),

    #"Changed Types" =
        Table.TransformColumnTypes(
            #"Combined Files",
            ExistingTypeMap
        ),

    // Normalize the original CertNow serial into uppercase hexadecimal.
    #"Normalized Serial" =
        Table.TransformColumns(
            #"Changed Types",
            {
                {
                    "Serial",
                    each
                        let
                            SerialText =
                                if _ = null then
                                    ""
                                else
                                    Text.From(_),

                            HexOnly =
                                Text.Upper(
                                    Text.Select(
                                        SerialText,
                                        {
                                            "0".."9",
                                            "A".."F",
                                            "a".."f"
                                        }
                                    )
                                )
                        in
                            if HexOnly = "" then
                                null
                            else
                                HexOnly,
                    type nullable text
                }
            }
        ),

    #"Filtered Blank Serials" =
        Table.SelectRows(
            #"Normalized Serial",
            each
                [Serial] <> null
                    and [Serial] <> ""
        ),

    // Newest export first for each serial.
    #"Sorted for Deduplication" =
        Table.Sort(
            #"Filtered Blank Serials",
            {
                {"Serial", Order.Ascending},
                {"export_date", Order.Descending},
                {"Source File", Order.Descending}
            }
        ),

    // Ensures Table.Distinct keeps the first row from the sorted table.
    #"Buffered Sorted Data" =
        Table.Buffer(
            #"Sorted for Deduplication"
        ),

    // Retain only the newest occurrence of each certificate.
    #"Kept Latest Serial" =
        Table.Distinct(
            #"Buffered Sorted Data",
            {"Serial"}
        )
in
    #"Kept Latest Serial"
