let
    // CertNow exports contain two date formats:
    //   AM/PM present  -> US format: M/d/yyyy h:mm:ss tt
    //   No AM/PM       -> UK format: dd/MM/yyyy HH:mm:ss
    ParseCertNowDateTime = (Value as any) as nullable datetime =>
        let
            RawValue =
                if Value = null then
                    null
                else
                    Text.Trim(Text.From(Value)),

            UpperValue =
                if RawValue = null then
                    ""
                else
                    Text.Upper(RawValue),

            HasAmPm =
                Text.EndsWith(UpperValue, " AM")
                    or Text.EndsWith(UpperValue, " PM"),

            PrimaryCulture =
                if HasAmPm then
                    "en-US"
                else
                    "en-GB",

            SecondaryCulture =
                if HasAmPm then
                    "en-GB"
                else
                    "en-US",

            ParsedValue =
                if RawValue = null or RawValue = "" then
                    null
                else
                    try
                        DateTime.FromText(
                            RawValue,
                            [Culture = PrimaryCulture]
                        )
                    otherwise
                        try
                            DateTime.FromText(
                                RawValue,
                                [Culture = SecondaryCulture]
                            )
                        otherwise
                            null
        in
            ParsedValue,


    // Keep the folder path selected through Data > Get Data > From Folder.
    Source =
        Folder.Files(
            "C:\Users\Downloads"
        ),


    // Import non-hidden CSV files whose names begin with Export_.
    #"Filtered Export CSV Files" =
        Table.SelectRows(
            Source,
            each
                Text.Lower([Extension]) = ".csv"
                    and Text.StartsWith(
                        [Name],
                        "Export_",
                        Comparer.OrdinalIgnoreCase
                    )
                    and Record.FieldOrDefault(
                        [Attributes],
                        "Hidden",
                        false
                    ) <> true
        ),


    #"Sorted Files" =
        Table.Sort(
            #"Filtered Export CSV Files",
            {
                {"Name", Order.Ascending}
            }
        ),


    // Import every matching file and add its source filename and export date.
    #"Imported Files" =
        Table.AddColumn(
            #"Sorted Files",
            "Imported Data",
            (CurrentFile as record) as table =>
                let
                    // Expected filename:
                    // Export_2026-07-23_something.csv
                    ExportDate =
                        try
                            Date.FromText(
                                Text.Middle(
                                    CurrentFile[Name],
                                    7,
                                    10
                                ),
                                [
                                    Format = "yyyy-MM-dd",
                                    Culture = "en-US"
                                ]
                            )
                        otherwise
                            try
                                Date.From(
                                    CurrentFile[Date modified]
                                )
                            otherwise
                                null,

                    CsvData =
                        Csv.Document(
                            CurrentFile[Content],
                            [
                                Delimiter = ",",
                                Encoding = 1252,
                                QuoteStyle = QuoteStyle.Csv
                            ]
                        ),

                    PromotedHeaders =
                        Table.PromoteHeaders(
                            CsvData,
                            [PromoteAllScalars = true]
                        ),

                    AddedSourceFile =
                        Table.AddColumn(
                            PromotedHeaders,
                            "Source File",
                            each CurrentFile[Name],
                            type text
                        ),

                    AddedExportDate =
                        Table.AddColumn(
                            AddedSourceFile,
                            "export_date",
                            each ExportDate,
                            type nullable date
                        )
                in
                    AddedExportDate,
            type table
        ),


    #"Combined Files" =
        if Table.RowCount(#"Imported Files") = 0 then
            #table({}, {})
        else
            Table.Combine(
                #"Imported Files"[Imported Data]
            ),


    // Valid From and Valid To must remain text until parsed using
    // the mixed US/UK date-format function.
    TypeMap =
        {
            {"Serial", type text},
            {"export_date", type date},
            {"Source File", type text},

            {"Managed DN", type text},
            {"Management Type", type text},
            {"Processing Disabled", type logical},
            {"In Error", type logical},
            {"Status", type text},
            {"Revocation Status", type text},
            {"Description", type text},
            {"Processing Stage", type text},
            {"Contact(s)", type text},
            {"Approver(s)", type text},
            {"Last Validation State Update", type text},
            {"Validation State", type text},
            {"Last Validation", type text},
            {"Last Validation Result", type text},
            {"Private Key Stored", type logical},
            {"Certificate Stored", type logical},
            {"CSR Stored", type logical},

            {"Subject DN", type text},
            {"Issuer DN", type text},
            {"Subject Alt Name (DNS)", type text},
            {"Subject Alt Name (Email)", type text},
            {"Subject Alt Name (IP)", type text},
            {"Subject Alt Name (UPN)", type text},
            {"Subject Alt Name (URI)", type text},

            {"Common Name", type text},
            {"Organization", type text},
            {"Organizational Unit", type text},
            {"Country", type text},
            {"State", type text},
            {"City", type text},

            {"Valid From", type text},
            {"Valid To", type text},

            {"Signature Algorithm", type text},
            {"Key Algorithm", type text},
            {"Key Size", Int64.Type},
            {"ECC Curve", type text},
            {"Key Usage", type text},
            {"Enhanced Key Usage", type text},
            {"Type", type text},
            {"Certificate Authority Template", type text},
            {"Number of Associations", Int64.Type},

            {
                "B5. Is this certificate installed off Barclays' premises?",
                type text
            },
            {
                "F3. Non Compliance Risk Gap Description",
                type text
            },
            {"1. OU1", type text},
            {
                "E3. Second Additional Notification (30 Days)",
                type text
            },
            {"F2. Target Remediation Date", type text},
            {"X1. Reference", type text},
            {"B6. Off Premises Contact", type text},
            {"Z7. Previous Serial Number", type text},
            {"B3. Environment", type text},
            {"X2. Previous Requester Email", type text},
            {"Z5. Authoriser Name", type text},
            {"C1. ITSI Correlation ID", type text},
            {"B4. Change Number", type text},
            {
                "E1. Early Additional Notification (120 Days)",
                type text
            },
            {"7. Private key storage", type text},
            {"D4. Navigator ID/OrderBook", type text},
            {"A2. ServiceFirst Group", type text},
            {"Z6. Service Owner Email", type text},
            {"C2. Transaction Cycle", type text},
            {
                "E4. Authoriser/Escalation Notification",
                type text
            },
            {"C3. IT Service Instance", type text},
            {
                "F1. Non Compliance Risk Gap Reference",
                type text
            },
            {"4. Extended_Key_Usage", type text},
            {"Z4. Requester Name", type text},
            {"3. OU3", type text},
            {"6. Override_Validity", type text},
            {"B1. Purpose", type text},
            {"A3. ServiceFirst Group Email", type text},
            {"X3. Previous Change Number", type text},
            {"2. OU2", type text},
            {
                "E2. First Additional Notification (60 Days)",
                type text
            },
            {"B2. Host Name", type text},
            {"C4. ITSI Description", type text},
            {"X4. Thumbprint", type text},
            {"D2. Project Name", type text},
            {"D3. Project Manager", type text},
            {"A1. Requester Email", type text}
        },


    // Apply types only to columns that exist in the current exports.
    ExistingTypeMap =
        List.Select(
            TypeMap,
            each
                List.Contains(
                    Table.ColumnNames(#"Combined Files"),
                    _{0}
                )
        ),


    #"Changed Types" =
        Table.TransformColumnTypes(
            #"Combined Files",
            ExistingTypeMap
        ),


    // Parse Valid From and Valid To independently using the detected format.
    ExistingDateTransforms =
        List.Select(
            {
                {
                    "Valid From",
                    each ParseCertNowDateTime(_),
                    type nullable datetime
                },
                {
                    "Valid To",
                    each ParseCertNowDateTime(_),
                    type nullable datetime
                }
            },
            each
                List.Contains(
                    Table.ColumnNames(#"Changed Types"),
                    _{0}
                )
        ),


    #"Parsed Certificate Dates" =
        Table.TransformColumns(
            #"Changed Types",
            ExistingDateTransforms
        ),


    // Normalize the original CertNow serial:
    // uppercase hexadecimal without separators.
    // Leading zeroes are preserved.
    #"Normalized Serial" =
        Table.TransformColumns(
            #"Parsed Certificate Dates",
            {
                {
                    "Serial",
                    each
                        let
                            SerialText =
                                if _ = null then
                                    ""
                                else
                                    Text.From(_),

                            HexOnly =
                                Text.Upper(
                                    Text.Select(
                                        SerialText,
                                        {
                                            "0".."9",
                                            "A".."F",
                                            "a".."f"
                                        }
                                    )
                                )
                        in
                            if HexOnly = "" then
                                null
                            else
                                HexOnly,
                    type nullable text
                }
            }
        ),


    #"Filtered Blank Serials" =
        Table.SelectRows(
            #"Normalized Serial",
            each
                [Serial] <> null
                    and [Serial] <> ""
        ),


    // Place the newest export first for every serial.
    #"Sorted for Deduplication" =
        Table.Sort(
            #"Filtered Blank Serials",
            {
                {"Serial", Order.Ascending},
                {"export_date", Order.Descending},
                {"Source File", Order.Descending}
            }
        ),


    // Ensures Table.Distinct retains the first row from the sorted table.
    #"Buffered Sorted Data" =
        Table.Buffer(
            #"Sorted for Deduplication"
        ),


    // Keep only the newest CertNow record for each serial.
    #"Kept Latest Serial" =
        Table.Distinct(
            #"Buffered Sorted Data",
            {"Serial"}
        )
in
    #"Kept Latest Serial"
