let
    Source =
        Folder.Files(
            "C:\Users\*\Data Sources\F5 Certificates"
        ),

    #"Filtered Certificate Usage Files" =
        Table.SelectRows(
            Source,
            each
                Text.Lower([Extension]) = ".tsv"
                    and Text.StartsWith(
                        [Name],
                        "f5_certificate_usage",
                        Comparer.OrdinalIgnoreCase
                    )
                    and Record.FieldOrDefault(
                        [Attributes],
                        "Hidden",
                        false
                    ) <> true
        ),

    #"Sorted Files" =
        Table.Sort(
            #"Filtered Certificate Usage Files",
            {
                {"Name", Order.Ascending}
            }
        ),

    #"Imported Files" =
        Table.AddColumn(
            #"Sorted Files",
            "Imported Data",
            (CurrentFile as record) as table =>
                let
                    TSVData =
                        Csv.Document(
                            CurrentFile[Content],
                            [
                                Delimiter = "#(tab)",
                                Encoding = 1252,
                                QuoteStyle = QuoteStyle.None
                            ]
                        ),

                    PromotedHeaders =
                        Table.PromoteHeaders(
                            TSVData,
                            [PromoteAllScalars = true]
                        ),

                    AddedSourceFile =
                        Table.AddColumn(
                            PromotedHeaders,
                            "Source File",
                            each CurrentFile[Name],
                            type text
                        )
                in
                    AddedSourceFile,
            type table
        ),

    #"Combined Files" =
        if Table.RowCount(#"Imported Files") = 0 then
            #table({}, {})
        else
            Table.Combine(
                #"Imported Files"[Imported Data]
            ),

    #"Parsed Expiration Date" =
        if Table.HasColumns(
            #"Combined Files",
            "expiration_date"
        ) then
            Table.TransformColumns(
                #"Combined Files",
                {
                    {
                        "expiration_date",
                        each
                            try
                                let
                                    Parts =
                                        Splitter.SplitTextByWhitespace()(
                                            Text.Trim(Text.From(_))
                                        ),

                                    ParsedDate =
                                        Date.FromText(
                                            Parts{0}
                                                & " "
                                                & Parts{1}
                                                & " "
                                                & Parts{3},
                                            [Culture = "en-US"]
                                        ),

                                    ParsedTime =
                                        Time.FromText(
                                            Parts{2},
                                            [Culture = "en-US"]
                                        )
                                in
                                    #datetimezone(
                                        Date.Year(ParsedDate),
                                        Date.Month(ParsedDate),
                                        Date.Day(ParsedDate),
                                        Time.Hour(ParsedTime),
                                        Time.Minute(ParsedTime),
                                        Number.RoundDown(
                                            Time.Second(ParsedTime)
                                        ),
                                        0,
                                        0
                                    )
                            otherwise
                                null,
                        type nullable datetimezone
                    }
                }
            )
        else
            #"Combined Files",

    TypeMap =
        {
            {"host", type text},
            {"cert_name", type text},
            {"used_by_profile", type text},
            {"profile_used_by", type text},
            {"expiration_date", type datetimezone},
            {"security_type", type text},
            {"serial_number", type text},
            {"CU_username", type text},
            {"Organization", type text},
            {"CN", type text},
            {"Issuer_CN", type text},
            {"subject_alternative_name", type text},
            {"vip_destination", type text},
            {"vip_port", Int64.Type},
            {"vip_destination_resolved", type text},
            {"clientside_bits_in", Int64.Type},
            {"clientside_bits_out", Int64.Type},
            {"clientside_conns", Int64.Type},
            {"clientside_max_conns", Int64.Type},
            {"clientside_tot_conns", Int64.Type},
            {"availability_state", type text},
            {"enabled_state", type text},
            {"status_reason", type text},
            {"status_extra", type text},
            {"Source File", type text},
            {"export_date", type datetime}
        },

    ExistingTypeMap =
        List.Select(
            TypeMap,
            each
                List.Contains(
                    Table.ColumnNames(#"Parsed Expiration Date"),
                    _{0}
                )
        ),

    #"Changed Types" =
        Table.TransformColumnTypes(
            #"Parsed Expiration Date",
            ExistingTypeMap
        ),

    UsageKeyColumns =
        {
            "host",
            "cert_name",
            "used_by_profile",
            "profile_used_by"
        },

    // Sort once globally instead of sorting separately inside every group.
    #"Sorted Usage Instances" =
        Table.Sort(
            #"Changed Types",
            {
                {"host", Order.Ascending},
                {"cert_name", Order.Ascending},
                {"used_by_profile", Order.Ascending},
                {"profile_used_by", Order.Ascending},
                {"export_date", Order.Descending},
                {"Source File", Order.Descending}
            }
        ),

    // Buffering ensures Table.Distinct retains the first, newest row.
    #"Buffered Sorted Usage" =
        Table.Buffer(
            #"Sorted Usage Instances"
        ),

    #"Kept Latest Usage Instance" =
        Table.Distinct(
            #"Buffered Sorted Usage",
            UsageKeyColumns
        ),

    CurrentColumns =
        Table.ColumnNames(
            #"Kept Latest Usage Instance"
        ),

    ColumnsToMoveLast =
        List.Select(
            {
                "Source File",
                "export_date"
            },
            each List.Contains(CurrentColumns, _)
        ),

    FinalColumnOrder =
        List.RemoveItems(
            CurrentColumns,
            ColumnsToMoveLast
        )
            & ColumnsToMoveLast,

    #"Moved Source Information Last" =
        Table.ReorderColumns(
            #"Kept Latest Usage Instance",
            FinalColumnOrder,
            MissingField.Ignore
        )
in
    #"Moved Source Information Last"
