let
    InsertAfter = (
        Columns as list,
        Anchor as text,
        ColumnsToInsert as list
    ) as list =>
        let
            BaseColumns =
                List.RemoveItems(
                    Columns,
                    ColumnsToInsert
                ),

            AnchorPosition =
                List.PositionOf(
                    BaseColumns,
                    Anchor
                )
        in
            if AnchorPosition < 0 then
                BaseColumns & ColumnsToInsert
            else
                List.InsertRange(
                    BaseColumns,
                    AnchorPosition + 1,
                    ColumnsToInsert
                ),

    NormalizeText = (Value as any) as nullable text =>
        let
            Result =
                if Value = null then
                    null
                else
                    Text.Upper(
                        Text.Trim(
                            Text.From(Value)
                        )
                    )
        in
            if Result = null or Result = "" then
                null
            else
                Result,

    Source =
        stg_F5_Certificate_Usage_Core,

    ClusterLookup =
        Table.Buffer(
            stg_Cluster_Host_Map
        ),

    CertificateUsageLookup =
        Table.Buffer(
            stg_Certificate_Usage_Map
        ),

    CertNowLookup =
        Table.Buffer(
            stg_CertNow_Latest
        ),

    SPDWLookup =
        Table.Buffer(
            stg_SPDW_ITSI_Details
        ),

    CertNowColumns =
        List.RemoveItems(
            Table.ColumnNames(
                CertNowLookup
            ),
            {
                "Serial"
            }
        ),

    SPDWColumns =
        List.RemoveItems(
            Table.ColumnNames(
                SPDWLookup
            ),
            {
                "ITSI Correlation Key"
            }
        ),

    ClusterColumns =
        {
            "Cluster Member",
            "Cluster Representative",
            "Migration Role",
            "Migration Package",
            "Migration Date"
        },

    CertificateSummaryColumns =
        {
            "Certificate Representative",
            "Certificate Usage Count",
            "Certificate Used By"
        },


    //=====================================================
    // CLUSTER / MIGRATION INFORMATION
    //=====================================================

    #"Merged Cluster Information" =
        Table.NestedJoin(
            Source,
            {
                "_HostKey"
            },
            ClusterLookup,
            {
                "_HostKey"
            },
            "Cluster Information",
            JoinKind.LeftOuter
        ),

    #"Expanded Cluster Information" =
        Table.ExpandTableColumn(
            #"Merged Cluster Information",
            "Cluster Information",
            {
                "Cluster Member",
                "Cluster Representative",
                "Migration Role",
                "Migration Package",
                "Migration Date"
            },
            {
                "Cluster Member",
                "Cluster Representative",
                "Migration Role",
                "Migration Package",
                "Migration Date"
            }
        ),


    //=====================================================
    // CERTIFICATE REPRESENTATIVE / USAGE SUMMARY
    //=====================================================

    #"Merged Certificate Usage Summary" =
        Table.NestedJoin(
            #"Expanded Cluster Information",
            {
                "_UsageKey"
            },
            CertificateUsageLookup,
            {
                "_UsageKey"
            },
            "Certificate Usage Summary",
            JoinKind.LeftOuter
        ),

    #"Expanded Certificate Usage Summary" =
        Table.ExpandTableColumn(
            #"Merged Certificate Usage Summary",
            "Certificate Usage Summary",
            {
                "Certificate Representative",
                "Certificate Usage Count",
                "Certificate Used By"
            },
            {
                "Certificate Representative",
                "Certificate Usage Count",
                "Certificate Used By"
            }
        ),


    //=====================================================
    // CERTNOW INFORMATION
    //=====================================================

    #"Merged CertNow" =
        Table.NestedJoin(
            #"Expanded Certificate Usage Summary",
            {
                "_NormalizedSerial"
            },
            CertNowLookup,
            {
                "Serial"
            },
            "CertNow Match",
            JoinKind.LeftOuter
        ),

    #"Expanded CertNow" =
        Table.ExpandTableColumn(
            #"Merged CertNow",
            "CertNow Match",
            CertNowColumns,
            CertNowColumns
        ),


    //=====================================================
    // SPDW ITSI INFORMATION
    //=====================================================

    #"Added ITSI Correlation Key" =
        Table.AddColumn(
            #"Expanded CertNow",
            "_ITSICorrelationKey",
            each
                NormalizeText(
                    [#"CertNow_C1. ITSI Correlation ID"]
                ),
            type nullable text
        ),

    #"Merged SPDW ITSI Information" =
        Table.NestedJoin(
            #"Added ITSI Correlation Key",
            {
                "_ITSICorrelationKey"
            },
            SPDWLookup,
            {
                "ITSI Correlation Key"
            },
            "SPDW ITSI Information",
            JoinKind.LeftOuter
        ),

    #"Expanded SPDW ITSI Information" =
        Table.ExpandTableColumn(
            #"Merged SPDW ITSI Information",
            "SPDW ITSI Information",
            SPDWColumns,
            SPDWColumns
        ),


    //=====================================================
    // CLEANUP
    //=====================================================

    #"Removed Technical Columns" =
        Table.RemoveColumns(
            #"Expanded SPDW ITSI Information",
            {
                "_HostKey",
                "_NormalizedSerial",
                "_UsageKey",
                "_ITSICorrelationKey"
            }
        ),


    //=====================================================
    // COLUMN ORDER
    //=====================================================

    ColumnOrderWithCluster =
        InsertAfter(
            Table.ColumnNames(
                #"Removed Technical Columns"
            ),
            "host",
            ClusterColumns
        ),

    ColumnOrderWithCertificateSummary =
        InsertAfter(
            ColumnOrderWithCluster,
            "cert_name",
            CertificateSummaryColumns
        ),

    ColumnOrderWithCertNow =
        InsertAfter(
            ColumnOrderWithCertificateSummary,
            "serial_number",
            CertNowColumns
        ),

    FinalColumnOrder =
        InsertAfter(
            ColumnOrderWithCertNow,
            "CertNow_C1. ITSI Correlation ID",
            SPDWColumns
        ),

    #"Reordered Columns" =
        Table.ReorderColumns(
            #"Removed Technical Columns",
            FinalColumnOrder,
            MissingField.Ignore
        )
in
    #"Reordered Columns"
