let
    // Keep the folder path generated by Data > Get Data > From Folder
    Source =
        Folder.Files(
            "C:\Users\"
        ),

    // Keep non-hidden TSV files whose names start with f5_certificate_usage
    #"Filtered Certificate Usage Files" =
        Table.SelectRows(
            Source,
            each
                Text.Lower([Extension]) = ".tsv"
                    and Text.StartsWith(
                        [Name],
                        "f5_certificate_usage",
                        Comparer.OrdinalIgnoreCase
                    )
                    and Record.FieldOrDefault(
                        [Attributes],
                        "Hidden",
                        false
                    ) <> true
        ),

    #"Sorted Files" =
        Table.Sort(
            #"Filtered Certificate Usage Files",
            {
                {"Name", Order.Ascending}
            }
        ),

    // Import each matching TSV and add its filename to every row
    #"Imported Files" =
        Table.AddColumn(
            #"Sorted Files",
            "Imported Data",
            (CurrentFile as record) as table =>
                let
                    TSVData =
                        Csv.Document(
                            CurrentFile[Content],
                            [
                                Delimiter = "#(tab)",
                                Columns = 25,
                                Encoding = 1252,
                                QuoteStyle = QuoteStyle.None
                            ]
                        ),

                    #"Promoted Headers" =
                        Table.PromoteHeaders(
                            TSVData,
                            [PromoteAllScalars = true]
                        ),

                    #"Added Source File" =
                        Table.AddColumn(
                            #"Promoted Headers",
                            "Source File",
                            each CurrentFile[Name],
                            type text
                        )
                in
                    #"Added Source File",
            type table
        ),

    // Append all imported files
    #"Combined Files" =
        Table.Combine(
            #"Imported Files"[Imported Data]
        ),

    // Convert F5 expiration-date text into a datetimezone value
    #"Parsed Expiration Date" =
        Table.TransformColumns(
            #"Combined Files",
            {
                {
                    "expiration_date",
                    each
                        try
                            let
                                Parts =
                                    Splitter.SplitTextByWhitespace()(
                                        Text.Trim(Text.From(_))
                                    ),

                                ParsedDate =
                                    Date.FromText(
                                        Parts{0}
                                            & " "
                                            & Parts{1}
                                            & " "
                                            & Parts{3},
                                        [Culture = "en-US"]
                                    ),

                                ParsedTime =
                                    Time.FromText(
                                        Parts{2},
                                        [Culture = "en-US"]
                                    )
                            in
                                #datetimezone(
                                    Date.Year(ParsedDate),
                                    Date.Month(ParsedDate),
                                    Date.Day(ParsedDate),
                                    Time.Hour(ParsedTime),
                                    Time.Minute(ParsedTime),
                                    Number.RoundDown(
                                        Time.Second(ParsedTime)
                                    ),
                                    0,
                                    0
                                )
                        otherwise
                            null,
                    type datetimezone
                }
            }
        ),

    #"Changed Type" =
        Table.TransformColumnTypes(
            #"Parsed Expiration Date",
            {
                {"host", type text},
                {"cert_name", type text},
                {"used_by_profile", type text},
                {"profile_used_by", type text},
                {"expiration_date", type datetimezone},
                {"security_type", type text},
                {"serial_number", type text},
                {"CU_username", type text},
                {"Organization", type text},
                {"CN", type text},
                {"Issuer_CN", type text},
                {"subject_alternative_name", type text},
                {"vip_destination", type text},
                {"vip_port", Int64.Type},
                {"vip_destination_resolved", type text},
                {"clientside_bits_in", Int64.Type},
                {"clientside_bits_out", Int64.Type},
                {"clientside_conns", Int64.Type},
                {"clientside_max_conns", Int64.Type},
                {"clientside_tot_conns", Int64.Type},
                {"availability_state", type text},
                {"enabled_state", type text},
                {"status_reason", type text},
                {"status_extra", type text},
                {"Source File", type text},
                {"export_date", type datetime}
            }
        ),

    // Move Source File and export_date to the far-right end
    #"Moved Source File and Export Date Last" =
        Table.ReorderColumns(
            #"Changed Type",
            List.RemoveItems(
                Table.ColumnNames(#"Changed Type"),
                {
                    "Source File",
                    "export_date"
                }
            )
                & {
                    "Source File",
                    "export_date"
                }
        )
in
    #"Moved Source File and Export Date Last"
