let
    InsertAfter = (
        Columns as list,
        Anchor as text,
        ColumnsToInsert as list
    ) as list =>
        let
            BaseColumns =
                List.RemoveItems(
                    Columns,
                    ColumnsToInsert
                ),

            AnchorPosition =
                List.PositionOf(
                    BaseColumns,
                    Anchor
                )
        in
            if AnchorPosition < 0 then
                BaseColumns & ColumnsToInsert
            else
                List.InsertRange(
                    BaseColumns,
                    AnchorPosition + 1,
                    ColumnsToInsert
                ),

    Source =
        stg_F5_Certificate_Usage_Core,

    ClusterLookup =
        Table.Buffer(
            stg_Cluster_Host_Map
        ),

    CertificateUsageLookup =
        Table.Buffer(
            stg_Certificate_Usage_Map
        ),

    CertNowLookup =
        Table.Buffer(
            stg_CertNow_Latest
        ),

    CertNowColumns =
        List.RemoveItems(
            Table.ColumnNames(
                CertNowLookup
            ),
            {"Serial"}
        ),

    ClusterColumns =
        {
            "Cluster Member",
            "Cluster Representative",
            "Migration Role",
            "Migration Package",
            "Migration Date"
        },

    CertificateSummaryColumns =
        {
            "Certificate Representative",
            "Certificate Usage Count",
            "Certificate Used By"
        },

    #"Merged Cluster Information" =
        Table.NestedJoin(
            Source,
            {"_HostKey"},
            ClusterLookup,
            {"_HostKey"},
            "Cluster Information",
            JoinKind.LeftOuter
        ),

    #"Expanded Cluster Information" =
        Table.ExpandTableColumn(
            #"Merged Cluster Information",
            "Cluster Information",
            {
                "Cluster Member",
                "Cluster Representative",
                "Migration Role",
                "Migration Package",
                "Migration Date"
            },
            {
                "Cluster Member",
                "Cluster Representative",
                "Migration Role",
                "Migration Package",
                "Migration Date"
            }
        ),

    #"Merged Certificate Usage Summary" =
        Table.NestedJoin(
            #"Expanded Cluster Information",
            {"_UsageKey"},
            CertificateUsageLookup,
            {"_UsageKey"},
            "Certificate Usage Summary",
            JoinKind.LeftOuter
        ),

    #"Expanded Certificate Usage Summary" =
        Table.ExpandTableColumn(
            #"Merged Certificate Usage Summary",
            "Certificate Usage Summary",
            {
                "Certificate Representative",
                "Certificate Usage Count",
                "Certificate Used By"
            },
            {
                "Certificate Representative",
                "Certificate Usage Count",
                "Certificate Used By"
            }
        ),

    #"Merged CertNow" =
        Table.NestedJoin(
            #"Expanded Certificate Usage Summary",
            {"_NormalizedSerial"},
            CertNowLookup,
            {"Serial"},
            "CertNow Match",
            JoinKind.LeftOuter
        ),

    #"Expanded CertNow" =
        Table.ExpandTableColumn(
            #"Merged CertNow",
            "CertNow Match",
            CertNowColumns,
            CertNowColumns
        ),

    #"Removed Technical Columns" =
        Table.RemoveColumns(
            #"Expanded CertNow",
            {
                "_HostKey",
                "_NormalizedSerial",
                "_UsageKey"
            }
        ),

    ColumnOrderWithCluster =
        InsertAfter(
            Table.ColumnNames(
                #"Removed Technical Columns"
            ),
            "host",
            ClusterColumns
        ),

    ColumnOrderWithCertificateSummary =
        InsertAfter(
            ColumnOrderWithCluster,
            "cert_name",
            CertificateSummaryColumns
        ),

    FinalColumnOrder =
        InsertAfter(
            ColumnOrderWithCertificateSummary,
            "serial_number",
            CertNowColumns
        ),

    #"Reordered Columns" =
        Table.ReorderColumns(
            #"Removed Technical Columns",
            FinalColumnOrder,
            MissingField.Ignore
        )
in
    #"Reordered Columns"
