let
    CertNowFields =
        {
            "Managed DN",
            "Description",
            "Subject Alt Name (DNS)",
            "Common Name",
            "Valid To",
            "C1. ITSI Correlation ID",
            "D4. Navigator ID/OrderBook",
            "B4. Change Number",
            "E1. Early Additional Notification (120 Days)",
            "A2. ServiceFirst Group",
            "Z6. Service Owner Email",
            "E4. Authoriser/Escalation Notification",
            "C3. IT Service Instance",
            "A3. ServiceFirst Group Email",
            "E2. First Additional Notification (60 Days)",
            "A1. Requester Email",
            "D2. Project Name",
            "D3. Project Manager"
        },

    Source =
        CertNow,

    #"Selected Columns" =
        Table.SelectColumns(
            Source,
            {"Serial"} & CertNowFields,
            MissingField.UseNull
        ),

    PrefixRenames =
        List.Transform(
            CertNowFields,
            each
                {
                    _,
                    "CertNow_" & _
                }
        ),

    #"Prefixed CertNow Fields" =
        Table.RenameColumns(
            #"Selected Columns",
            PrefixRenames,
            MissingField.Ignore
        )
in
    #"Prefixed CertNow Fields"
