let
    SharePointFile =
        Binary.Buffer(
            Web.Contents(
                "https://,
                [
                    RelativePath =
                        "teams/"
                ]
            )
        ),

    Workbook =
        Excel.Workbook(
            SharePointFile,
            null,
            true
        ),

    Source =
        Workbook{
            [
                Item = "LB_List",
                Kind = "Table"
            ]
        }[Data],

    // Clean line breaks, tabs and repeated spaces from the headers.
    #"Cleaned Column Names" =
        Table.TransformColumnNames(
            Source,
            each
                Text.Combine(
                    List.Select(
                        Splitter.SplitTextByWhitespace()(
                            Text.Trim(_)
                        ),
                        each _ <> ""
                    ),
                    " "
                )
        ),

    #"Selected Columns" =
        Table.SelectColumns(
            #"Cleaned Column Names",
            {
                "Hostname",
                "Target Tenant Hostname",
                "Migration Package",
                "Migration Date"
            },
            MissingField.UseNull
        ),

    #"Safely Converted Values" =
        Table.TransformColumns(
            #"Selected Columns",
            {
                {
                    "Hostname",
                    each
                        if _ = null then
                            null
                        else
                            Text.From(_),
                    type nullable text
                },
                {
                    "Target Tenant Hostname",
                    each
                        if _ = null then
                            null
                        else
                            Text.From(_),
                    type nullable text
                },
                {
                    "Migration Package",
                    each
                        if _ = null then
                            null
                        else
                            Text.From(_),
                    type nullable text
                },
                {
                    "Migration Date",
                    each
                        try Date.From(_)
                        otherwise null,
                    type nullable date
                }
            }
        ),

    #"Source Hosts" =
        Table.RenameColumns(
            Table.SelectColumns(
                #"Safely Converted Values",
                {
                    "Hostname",
                    "Migration Package",
                    "Migration Date"
                }
            ),
            {
                {
                    "Hostname",
                    "Host Key"
                }
            }
        ),

    #"Added Source Role" =
        Table.AddColumn(
            #"Source Hosts",
            "Migration Role",
            each "SOURCE",
            type text
        ),

    #"Target Hosts" =
        Table.RenameColumns(
            Table.SelectColumns(
                #"Safely Converted Values",
                {
                    "Target Tenant Hostname",
                    "Migration Package",
                    "Migration Date"
                }
            ),
            {
                {
                    "Target Tenant Hostname",
                    "Host Key"
                }
            }
        ),

    #"Added Target Role" =
        Table.AddColumn(
            #"Target Hosts",
            "Migration Role",
            each "TARGET",
            type text
        ),

    #"Combined Host Mapping" =
        Table.Combine(
            {
                #"Added Source Role",
                #"Added Target Role"
            }
        ),

    #"Normalized Mapping Values" =
        Table.TransformColumns(
            #"Combined Host Mapping",
            {
                {
                    "Host Key",
                    each
                        if _ = null then
                            null
                        else
                            Text.Upper(
                                Text.Trim(
                                    Text.From(_)
                                )
                            ),
                    type nullable text
                },
                {
                    "Migration Package",
                    each
                        if _ = null then
                            null
                        else
                            Text.Trim(
                                Text.From(_)
                            ),
                    type nullable text
                }
            }
        ),

    #"Filtered Invalid Hosts" =
        Table.SelectRows(
            #"Normalized Mapping Values",
            each
                [Host Key] <> null
                    and [Host Key] <> ""
                    and [Host Key] <> "NO DATA"
        ),

    #"Removed Exact Duplicates" =
        Table.Distinct(
            #"Filtered Invalid Hosts"
        )
in
    #"Removed Exact Duplicates"
