let
    CertNowFields =
        {
            "Managed DN",
            "Description",
            "Subject Alt Name (DNS)",
            "Common Name",
            "Valid To",
            "C1. ITSI Correlation ID",
            "D4. Navigator ID/OrderBook",
            "B4. Change Number",
            "E1. Early Additional Notification (120 Days)",
            "A2. ServiceFirst Group",
            "Z6. Service Owner Email",
            "E4. Authoriser/Escalation Notification",
            "C3. IT Service Instance",
            "A3. ServiceFirst Group Email",
            "E2. First Additional Notification (60 Days)",
            "A1. Requester Email",
            "D2. Project Name",
            "D3. Project Manager"
        },

    Source =
        CertNow,

    #"Selected Columns" =
        Table.SelectColumns(
            Source,
            {
                "Serial",
                "export_date",
                "Source File"
            }
                & CertNowFields,
            MissingField.UseNull
        ),

    #"Prepared Merge Key and Date" =
        Table.TransformColumns(
            #"Selected Columns",
            {
                {
                    "Serial",
                    each
                        if _ = null then
                            null
                        else
                            Text.Upper(
                                Text.Trim(
                                    Text.From(_)
                                )
                            ),
                    type nullable text
                },
                {
                    "export_date",
                    each
                        try DateTime.From(_)
                        otherwise null,
                    type nullable datetime
                },
                {
                    "Source File",
                    each
                        if _ = null then
                            null
                        else
                            Text.From(_),
                    type nullable text
                }
            }
        ),

    #"Filtered Blank Serials" =
        Table.SelectRows(
            #"Prepared Merge Key and Date",
            each
                [Serial] <> null
                    and [Serial] <> ""
        ),

    // A single global sort is considerably faster than sorting each group.
    #"Sorted CertNow Rows" =
        Table.Sort(
            #"Filtered Blank Serials",
            {
                {"Serial", Order.Ascending},
                {"export_date", Order.Descending},
                {"Source File", Order.Descending}
            }
        ),

    #"Buffered Sorted CertNow" =
        Table.Buffer(
            #"Sorted CertNow Rows"
        ),

    #"Kept Latest Serial" =
        Table.Distinct(
            #"Buffered Sorted CertNow",
            {"Serial"}
        ),

    #"Selected Final Fields" =
        Table.SelectColumns(
            #"Kept Latest Serial",
            {"Serial"} & CertNowFields,
            MissingField.UseNull
        ),

    PrefixRenames =
        List.Transform(
            CertNowFields,
            each
                {
                    _,
                    "CertNow_" & _
                }
        ),

    #"Prefixed CertNow Fields" =
        Table.RenameColumns(
            #"Selected Final Fields",
            PrefixRenames,
            MissingField.Ignore
        )
in
    #"Prefixed CertNow Fields"
